### ISSUE TITLE
Error while bulding.

### ISSUE THREAD

**Issue by vadirajmkulkarni** [thuyen/signal#1]
Hi,

Thanks for creating this library it is very helpful.
While building the module using "python build.py" I'm observing the following error.
Note- I have installed pyfft and fftw3.

It'd be great if you could help me resolve this. have I missed anything?

Thanks & Regards,
Vadiraj Kulkarni

vadiraj@vadiraj-VirtualBox:~/Downloads/signal-master$ python build.py
generating /tmp/tmp6y2Ha1/torchsignal/siglib/lib_fft/_lib_fft.c
running build_ext
building 'torchsignal.siglib.lib_fft._lib_fft' extension
creating home
creating home/vadiraj
creating home/vadiraj/Downloads
creating home/vadiraj/Downloads/signal-master
creating home/vadiraj/Downloads/signal-master/torchsignal
creating home/vadiraj/Downloads/signal-master/torchsignal/src
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/include/python2.7 -c torchsignal/siglib/lib_fft/_lib_fft.c -o ./torchsignal/siglib/lib_fft/_lib_fft.o
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/include/python2.7 -c /home/vadiraj/Downloads/signal-master/torchsignal/src/fft.c -o ./home/vadiraj/Downloads/signal-master/torchsignal/src/fft.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security ./torchsignal/siglib/lib_fft/_lib_fft.o ./home/vadiraj/Downloads/signal-master/torchsignal/src/fft.o -lfftw3f -o ./torchsignal/siglib/lib_fft/torchsignal.siglib.lib_fft._lib_fft.so
Traceback (most recent call last):
  File "build.py", line 34, in <module>
    ffi.build()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 164, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 102, in _build_extension
    os.path.join(target_dir, libname))
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/tmp6y2Ha1/torchsignal.siglib.lib_fft._lib_fft.so'

**Comment by thuyen** [comment]
This is a package, so you should run `(sudo) python setup.py install` instead, assuming you have `pytorch` and `cffi` installed. I just updated the README. Cheers!

**Comment by vadirajmkulkarni** [comment]
Thanks for the quick reply! After running the above command "torchsignal" was installed and i'm able to import it. 
Thanks & Regards,
Vadiraj Kulkarni
